pipelines:
    branches:
      CDtest
    #'*.dev':
      - step:
          name: "Deploy_Pantheon"
          runs-on:
            - cd
          image: alpine:latest
          script:
            - git status
            - ls -la
