pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: "PHPCS"
              runs-on:
                - self.hosted
              image: wodby/drupal-php:8.3-dev-4.61.2
              caches:
                - composer
              script:
                - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
                - git fetch origin $BITBUCKET_BRANCH $BITBUCKET_PR_DESTINATION_BRANCH
                - composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
                - composer global require drupal/coder:8.3 --no-progress --prefer-dist
                - wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ~/bin
                - |
                  CHANGED_FILES=$(git diff --name-only origin/$BITBUCKET_BRANCH origin/$BITBUCKET_PR_DESTINATION_BRANCH -- | grep -E '\.(php|module|install|theme)$' || true)
                  echo "Changed files: $CHANGED_FILES"
                # Run phpcs check on changed files
                - |
                  if [ -n "$CHANGED_FILES" ]; then
                    ~/.composer/vendor/bin/phpcs --standard=Drupal,DrupalPractice $CHANGED_FILES --report=checkstyle | tee phpcs_report.txt
                  else
                    echo "No PHP files changed."
                    exit 0;
                  fi
                - cat phpcs_report.txt
                - ~/bin/reviewdog -f=checkstyle -name="PHPCS" -reporter=bitbucket-code-report -fail-level=any < phpcs_report.txt

          - step:
              name: "ESLint"
              runs-on:
                - self.hosted
              image: wodby/drupal-php:8.3-dev-4.61.2
              caches:
                - node
              script:
                - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
                - git fetch origin $BITBUCKET_BRANCH $BITBUCKET_PR_DESTINATION_BRANCH
                - sudo apk add npm
                - sudo npm install
                - wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ~/bin
                - |
                  CHANGED_FILES=$(git diff --name-only origin/$BITBUCKET_BRANCH origin/$BITBUCKET_PR_DESTINATION_BRANCH | grep -E '\.(js)$' || true)
                  echo "Changed files: $CHANGED_FILES"
                - npx eslint -c web/core/.eslintrc.json --no-error-on-unmatched-pattern $CHANGED_FILES | tee eslint_report.txt
                - ~/bin/reviewdog -f=eslint -name="ESLint" -reporter=bitbucket-code-report -fail-level=any < eslint_report.txt

          - step:
             name: "Trivy"
             runs-on:
                - self.hosted
             image: aquasec/trivy:latest
             script:
               - trivy fs --exit-code 1 --format table ./

  branches:
    'master':
      - step:
          name: "Build"
          runs-on:
            - self.hosted
          image: wodby/node:18-dev-1.14.2
          caches:
            - node # Cache node_modules for faster npm install t
          script:
            - cd web/themes/custom/bootcamp_theme/
            - npm install && npm run build
            - ls -la
          artifacts:
            - web/themes/custom/bootcamp_theme/js/**
            - web/themes/custom/bootcamp_theme/css/**
            - web/themes/custom/bootcamp_theme/sprite/**

      - step:
          name: "Deploy_Pantheon"
          runs-on:
            - self.hosted
          image: wodby/drupal-php:8.3-dev-4.61.2
          script:
             # Catching artifact files
            - cp -R web/themes/custom/bootcamp_theme/js /tmp/js
            - cp -R web/themes/custom/bootcamp_theme/css /tmp/css
            - cp -R web/themes/custom/bootcamp_theme/sprite /tmp/sprite
             # Installing terminus
            - sudo apk update && sudo apk add git curl
            - curl -L https://github.com/pantheon-systems/terminus/releases/download/3.6.0/terminus.phar --output terminus
            - chmod +x terminus
            - ./terminus self:update
            # Configuring git
            - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
            - git remote add pantheon $PANTHEON_REPO
            - ssh-keyscan -p 2222 $PANTHEON_HOST >> ~/.ssh/known_hosts
            - git fetch pantheon
            - git diff  $BITBUCKET_BRANCH pantheon/master
            # Merging changes
            - git checkout pantheon/master
            - git merge origin/$BITBUCKET_BRANCH --allow-unrelated-histories
            # Force adding the generated files, bypassing .gitignore
            - cp -Rf /tmp/js/* web/themes/custom/bootcamp_theme/js && git add -f web/themes/custom/bootcamp_theme/js
            - cp -Rf /tmp/css/* web/themes/custom/bootcamp_theme/css && git add -f web/themes/custom/bootcamp_theme/css
            - cp -Rf /tmp/sprite/* web/themes/custom/bootcamp_theme/sprite && git add -f web/themes/custom/bootcamp_theme/sprite
            - |
              if [[ -n $(git status --porcelain) ]]; then
                git commit -m "Add generated files"
              else
                echo "No changes to commit."
              fi
            - git push pantheon HEAD:master
            # Deploying using terminus
            - ./terminus auth:login --machine-token=$MACHINE_TOKEN_PANTHEON
            - ./terminus workflow:wait --commit $(git rev-parse HEAD) --max=300 -- liqx.dev
            - ./terminus drush liqx.dev -- deploy

definitions:
  caches:
    composer: ~/.composer/cache
    npm: ~/.npm
