pipelines:
  branches:
    CDtest:
    #'*.dev':
      - step:
          name: "Deploy_Pantheon"
          runs-on:
            - cd
          image: alpine:latest
          script:
            - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
            - git fetch origin
            - git --version
