image: wodby/drupal-php:8.3-dev-4.61.2

pipelines:
  default:
    - step:
        name: "Lint_PHPCS"
        runs-on:
          - ci
        script:
          - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
          - git fetch origin
          - composer install --no-progress
          - |
            CHANGED_FILES=$(git diff --name-only origin/$BITBUCKET_PR_SOURCE_BRANCH origin/$BITBUCKET_PR_DESTINATION_BRANCH | grep -E '\.(php|module|install|theme)$' || true)
            echo "Changed files: $CHANGED_FILES
            # Run linter only on changed files
          - |
            if [ -n "$CHANGED_FILES" ]; then
              vendor/bin/phpcs --standard=Drupal,DrupalPractice $CHANGED_FILES
            else
              echo "No PHP files changed."
            fi
