image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: Test
        runs-on:
          - linux
        script:
          - echo "linux"
          - uname -a
    - step:
        name: CI
        runs-on:
          - ci
        script:
          - echo "ci"
          - uname -a
    - step:
        name: CD
        runs-on:
          - cd
        script:
          - echo "cd"
          - uname -a
