pipelines:
  branches:
    CDtest:
    #'*.dev':
      - step:
          name: "Deploy_Pantheon"
          runs-on:
            - cd
          image: wodby/drupal-php:8.3-dev-4.61.2
          script:
             # Installing terminus
            - sudo apk update && sudo apk add git curl
            - curl -L https://github.com/pantheon-systems/terminus/releases/download/3.6.0/terminus.phar --output terminus
            - chmod +x terminus
            - ./terminus self:update
            # Configuring git
            - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
            - git remote add pantheon $PANTHEONE_REPO
            - cat ~/.ssh/known_hosts
            - git fetch pantheon
            - git remote -v
            - git diff  $BITBUCKET_BRANCH $BITBUCKET_CLONE_DIR pantheon/master
#
