pipelines:
  branches:
    CDtest:
    #'*.dev':
      - step:
          name: "Deploy_Pantheon"
          runs-on:
            - cd
          image: wodby/drupal-php:8.3-dev-4.61.2
          script:
             # Installing terminus
            - apt-get install -y git curl
            - curl -L https://github.com/pantheon-systems/terminus/releases/download/3.6.0/terminus.phar --output terminus
            - chmod +x terminus
            - ./terminus self:update
            # Configuring git
            - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
            - git remote add pantheon ssh://codeserver.dev.0220c6d2-7ed1-40fd-97ea-5f47e76c6a12@codeserver.dev.0220c6d2-7ed1-40fd-97ea-5f47e76c6a12.drush.in:2222/~/repository.git
            - git remote -v
