image: wodby/drupal-php:8.3-dev-4.61.2

pipelines:
  pull-requests:
    '**':
      - step:
          name: "Lint_PHPCS"
          runs-on:
            - ci
          script:
            - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
            - git fetch origin $BITBUCKET_BRANCH $BITBUCKET_PR_DESTINATION_BRANCH
            - composer install --no-progress
            - |
              CHANGED_FILES=$(git diff --name-only origin/$BITBUCKET_BRANCH origin/$BITBUCKET_PR_DESTINATION_BRANCH -- | grep -E '\.(php|module|install|theme)$' || true)
              echo "Changed files: $CHANGED_FILES"

            # Run linter only on changed files
            - |
              if [ -n "$CHANGED_FILES" ]; then
                vendor/bin/phpcs --standard=Drupal,DrupalPractice $CHANGED_FILES
              else
                echo "No PHP files changed."
              fi
