#!/bin/sh

# Get a list of changed files that match the specified extensions for PHPCS
CHANGED_FILES=$(git diff --cached --name-only | grep -E '\.php$|\.install$|\.module$|\.theme$')

# If there are no relevant changed files, skip PHPCS
if [ -z "$CHANGED_FILES" ]; then
  echo "No PHP-related files have changed, skipping PHPCS."
else
  # Run PHPCS on the changed files
  vendor/bin/phpcs --standard=Drupal,DrupalPractice $CHANGED_FILES --extensions=php,install,module,theme
fi

# Capture the exit code of PHPCS
PHPCS_STATUS=$?

# Get a list of changed files that match the specified extensions for ESLint
CHANGED_FILES=$(git diff --cached --name-only | grep -E '\.js$')

# If there are no relevant changed files, skip ESLint
if [ -z "$CHANGED_FILES" ]; then
  echo "No JS-related files have changed, skipping ESLINT."
else
  # Run ESLint on the changed files
  npx eslint $CHANGED_FILES
fi

# Capture the exit code of ESLint
ESLINT_STATUS=$?

# Exit with code according to PHPCS and ESLint

if [ $PHPCS_STATUS -ne 0 ] || [ $ESLINT_STATUS -ne 0 ]; then
  exit 1
else
  exit 0
fi

