name: Deploy to Remote Server

on:
  push:
    branches:
      - 'R8492_Configuration_of_CD'


#  workflow_run:
#    workflows: [PHPCS Check]
#    types:
#      - completed

jobs:
  deploy_to_remote:
    runs-on: ubuntu-latest
   # if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            set -e

            # Update files 
            cd /var/www/html || exit
            echo "Starting pulling--------------------------------------------------------------------"
            git pull origin master
            echo "Pull from remote success------------------------------------------------------------"

            # Install dependencies (e.g., via Composer)
            echo "Starting install dependencies process via composer----------------------------------"
            composer install --no-dev --optimize-autoloader
            echo "Installing success------------------------------------------------------------------"
            echo "Start deploy via drush--------------------------------------------------------------"
            vendor/bin/drush deploy
            echo "Deployment success------------------------------------------------------------------"

        env:
          SSH_USER: ${{ secrets.REMOTE_USER }}
          SSH_HOST: ${{ secrets.REMOTE_SERVER }}

