services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_TRANSACTION_ISOLATION: READ-COMMITTED
    volumes:
      - /var/www/html/back_sql:/docker-entrypoint-initdb.d
      - mariadb-datavolume:/var/lib/mysql

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "php"
    environment:
      PHP_EXTENSIONS_DISABLE: xhprof,spx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/www/html:/var/www/html:cached
      - php_ssh:/home/wodby/.ssh

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "nginx"
    depends_on:
      - php
    environment:
      NGINX_SET_REAL_IP_FROM: "0.0.0.0/0"
      NGINX_REAL_IP_HEADER: "CF-Connecting-IP"
      NGINX_REAL_IP_RECURSIVE: on
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - /var/www/html:/var/www/html:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`www.drupalliqx.pp.ua`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

  adminer:
    image: wodby/adminer:$ADMINER_TAG
    container_name: "adminer"
    depends_on:
      - mariadb
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.drupalliqx.pp.ua`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=myresolver"
      - "traefik.http.services.adminer.loadbalancer.server.port=9000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:$PHPMYADMIN_TAG
    container_name: "phpmyadmin"
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.drupalliqx.pp.ua`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  memcached:
    image: wodby/memcached:$MEMCACHED_TAG
    container_name: "memcached"
    environment:
      MEMCACHED_MEMORY_LIMIT: 64 # Memory limit in MB
      MEMCACHED_MAX_CONNECTIONS: 1024 # Maximum number of connections
    command: memcached -m 512 -t 4 -c 512 -vv
    ports:
      - "11211:11211"
    labels:
      - "traefik.enable=false"

  node:
    image: wodby/node:$NODE_TAG
    container_name: "node"
    working_dir: /var/www/html/web/themes/custom/bootcamp_theme
    volumes:
      - /var/www/html:/var/www/html
    command: sh -c 'npm install && npm run build'

  backup:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "backup"
    depends_on:
      - mariadb
      - php
    volumes:
      - /var/www/html:/var/www/html
      - /home/backups/files:/home/backups/files
    user: root
    command: >
      /bin/sh -c "echo '0 4 * * * /var/www/html/docker_under_portainer/backup.sh' > /etc/crontabs/wodby &&
                  crond -f -d 0"

  solr:
    image: wodby/solr:$SOLR_TAG
    container_name: "solr"
    environment:
      SOLR_DEFAULT_CONFIG_SET: $SOLR_DEFAULT_CONFIG_SET
      SOLR_HEAP: 1024m

    volumes:
     - solr-data:/opt/solr/server/solr # Volume for solr data

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solr.rule=Host(`solr.drupalliqx.pp.ua`)"
      - "traefik.http.routers.solr.entrypoints=websecure"
      - "traefik.http.routers.solr.tls.certresolver=myresolver"
      - "traefik.http.services.solr.loadbalancer.server.port=8983"
      #Auth
      - "traefik.http.middlewares.auth.basicauth.users=$BA_USER:$BA_PASSWORD"
      - "traefik.http.routers.solr.middlewares=auth"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTICSEARCH_TAG
    container_name: "elasticsearch"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

networks:
  default:
    external:
      name: traefik-net

volumes:
  mariadb-datavolume:
    driver: local
  php_ssh:
    driver: local
  solr-data:
    driver: local
  elasticsearch-data:
    driver: local
